from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    return LaunchDescription([
        Node(
            package='robosoccer_perception',
            executable='sensor_node',
            name='sensor_node',
            output='screen'
        ),
        Node(
            package='robosoccer_perception',
            executable='perception_node',
            name='perception_node',
            output='screen'
        ),
        Node(
            package='robosoccer_localization',
            executable='localization_node',
            name='localization_node',
            output='screen'
        ),
        Node(
            package='robosoccer_world_model',
            executable='world_model_node',
            name='world_model_node',
            output='screen'
        ),
        Node(
            package='robosoccer_behavior',
            executable='behavior_tree_node',
            name='behavior_tree_node',
            output='screen'
        ),
        Node(
            package='robosoccer_motion',
            executable='motion_planner_node',
            name='motion_planner_node',
            output='screen'
        ),
        Node(
            package='robosoccer_control',
            executable='biped_controller_node',
            name='biped_controller_node',
            output='screen'
        ),
        Node(
            package='robosoccer_firmware',
            executable='firmware_bridge_node',
            name='firmware_bridge_node',
            output='screen'
        ),
        Node(
            package='robosoccer_gamecontrol',
            executable='gamecontrol_node',
            name='gamecontrol_node',
            output='screen'
        ),
        Node(
            package='robosoccer_diagnostics',
            executable='diagnostics_node',
            name='diagnostics_node',
            output='screen'
        ),
    ])
